name: Deploy Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production   # <--- PENTING BANGET

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject ENV
        run: |
          mkdir -p public
          echo "window.__ENV = {
            WORKER_URL: '${{ secrets.WORKER_URL }}',
            ACCESS_PASSWORD: '${{ secrets.ACCESS_PASSWORD }}',
            CLIENT_TOKEN: '${{ secrets.CLIENT_TOKEN }}',
            API_KEY: '${{ secrets.API_KEY }}'
          };" > public/env.js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
